include $(GNUSTEP_MAKEFILES)/common.make

PACKAGE_NAME = netclasses
VERSION = 1.1.0
INTERFACE_VERSION = 1

SUBPROJECTS = Source 

include $(GNUSTEP_MAKEFILES)/aggregate.make
include GNUmakefile.postamble
