include $(GNUSTEP_MAKEFILES)/common.make

FRAMEWORK_NAME = netclasses 
VERSION = 1.1.0

netclasses_OBJC_FILES = NetBase.m NetTCP.m LineObject.m IRCObject.m 
netclasses_HEADER_FILES = NetBase.h NetTCP.h IRCObject.h LineObject.h 

GUI_LIB =

-include GNUmakefile.preamble
include $(GNUSTEP_MAKEFILES)/framework.make
-include GNUmakefile.postamble
