include $(GNUSTEP_MAKEFILES)/common.make

TOOL_NAME = backlight_helper

$(TOOL_NAME)_STANDARD_INSTALL=no

$(TOOL_NAME)_OBJC_FILES = backlight_main.m

$(TOOL_NAME)_NEEDS_GUI = no

-include GNUmakefile.preamble
include $(GNUSTEP_MAKEFILES)/tool.make
include $(GNUSTEP_MAKEFILES)/ctool.make
-include GNUmakefile.postamble
