#!/bin/bash

CONTROL_FILE="/tmp/$UID-launcher-control.pipe"

if [ "$1" == "doshowpanel" ];then
  #SEL=`nxpasteboard --selection | head -n 1`
  #echo "SEARCH_WORD='$SEL'"
  echo "WINDOW=visible"

elif [ "$1" == "dosearch" ];then
  source /dev/stdin

  echo "LOG: $SEARCH_TYPE"
  echo "LOG: $SEARCH_WORD"

  case "$SEARCH_TYPE" in
    "0")
      nxworkspace --open "man://$SEARCH_WORD"
      ;;
    "1")
      nxworkspace --open "info://$SEARCH_WORD"
      ;;
    "2")
      nxworkspace --open "dict://default/m:$SEARCH_WORD"
      ;;
    "3")
      nxworkspace --open "https://www.google.com/search?q=$SEARCH_WORD"
      ;;
    "4")
      bash ./Resources/find_ref_api "$SEARCH_WORD"
      ;;
  esac
fi

rm $CONTROL_FILE 2>/dev/null
mkfifo $CONTROL_FILE

while true ;do
  echo "LOG: reading control file $CONTROL_FILE"

  read -r LINE < $CONTROL_FILE
  echo "SEARCH_WORD='$LINE'"
  echo "WINDOW=visible"
done
