#!/bin/perl

$BASE_DIR = $ARGV[0];
$QUERY = $ARGV[1];
$TYPE = $ARGV[2];

$cmd = "recollq";
$qt = "-a";

if ($TYPE == 1) {
  $qt = "-f";
  $QUERY = "$QUERY*";
}

if (! -d $BASE_DIR) {
  print("X:file not found\n");
  exit 1;
}

if ($QUERY eq "") {
  print("X:no query specified\n");
  exit 1;
}

$cmd = "$cmd $qt -C -c \"$BASE_DIR\" -A \"$QUERY\"";
print("$cmd\n");

open(IN, "$cmd |");
while(<IN>) {
  chomp();
  #print("$_\n");
  if (m/^([\w\-]+\/[\w\-]+)\s+\[(.*?)\]\s+\[(.*?)\]/) {
    $mine = $1;
    $url = $2;
    $title = $3;
    $abstract = "";
    $in_abstract = 0;

    $title = "Unknown" if ($title eq "");
  }
  elsif (m/^ABSTRACT/) {
    $in_abstract = 1;
  }
  elsif (m/^\/ABSTRACT/) {
    print("T:$title\n");
    print("U:$url\n");

    $url = "";
    $in_abstract = 0;
  }
  elsif ($url ne "" && $in_abstract) {
    $abstract .= "$_\n";
  }
}
close(IN);
