#!/usr/bin/env bash

exec 100> /tmp/gsde-preferences-$GS_DESKTOP_ID.lock
flock -n 100 || exit 1

function update_screen {
  PID=`cat /tmp/$UID-wm.pid 2>/dev/null`
  if [ -n "$PID" ];then
    kill -USR1 "$PID"
  fi

  sleep 0.5

  PID=`cat /tmp/$UID-picom.pid 2>/dev/null`
  if [ -n "$PID" ];then
    kill -USR1 "$PID" 2>/dev/null
  fi

  xrefresh
  sleep 1
}

if [ "$1" = "keyboard" ];then
  if [ -f ~/.Xmodmap ];then
    xmodmap ~/.Xmodmap
  fi
fi

if [ "$1" = "screen" ];then
  update_screen
fi

if [ "$1" = "layout" ];then
  # layout should come after the screen change
  autorandr --force -s gsdesktop
fi
