#!/usr/bin/env bash

if [ "$1" == "keyboard" ];then
  if [ -f ~/.Xmodmap ];then
    xmodmap ~/.Xmodmap
  fi
fi

if [ "$1" == "screen" ];then
  PID=`cat /tmp/$UID-picom.pid 2>/dev/null`
  if [ -n "$PID" ];then
    kill -USR1 "$PID" 2>/dev/null
  fi
fi
