.\"nxworkspace(1) man page
.\"put together by onflapp
.\"Copyright (C) 2020 Free Software Foundation, Inc.
.\"Copying and distribution of this file, with or without modification,
.\"are permitted in any medium without royalty provided the copyright
.\"notice and this notice are preserved.
.\"
.\"Process this file with
.\"groff -man -Tascii nxworkspace.1
.\"
.TH NXAUDIO 1 "August 2020" GNUstep "NEXTSPACE System Manual"
.SH NAME
nxaudio \- control audio volume from the command line
.SH SYNOPSIS
.B nxaudio +|- <value>
.P
.SH DESCRIPTION
.P
Control audio volume from the command line.

.SH OPTIONS
.P
+ or \- value
.P
