.\"nxbrowser(1) man page
.\"put together by onflapp
.\"Copyright (C) 2020 Free Software Foundation, Inc.
.\"Copying and distribution of this file, with or without modification,
.\"are permitted in any medium without royalty provided the copyright
.\"notice and this notice are preserved.
.\"
.\"Process this file with
.\"groff -man -Tascii nxbrowser.1
.\"
.TH NXBROWSER 1 "August 2020" GSDE "User Manual"
.SH NAME
nxbrowser \- launch browser from command line
.SH SYNOPSIS
.B nxbrowser [--open <url>] [--search <text>]
.P
.SH DESCRIPTION
.P
nxbrowser will open URL in the WebBrowser.app

.SH OPTIONS
.P
--open <url>        open url in the WebBrowser
--search <text>     search text using hte WebBrowser
.P
