.\"nxpasteboard(1) man page
.\"put together by onflapp
.\"Copyright (C) 2020 Free Software Foundation, Inc.
.\"Copying and distribution of this file, with or without modification,
.\"are permitted in any medium without royalty provided the copyright
.\"notice and this notice are preserved.
.\"
.\"Process this file with
.\"groff -man -Tascii nxcolors.1
.\"
.TH NXCOLORS 1 "August 2020" GSDE "User Manual"
.SH NAME
nxcolors \- print out system colors
.SH SYNOPSIS
.B  nxcolors
.P
.SH DESCRIPTION
.P
