.\"nxdisplay(1) man page
.\"put together by onflapp
.\"Copyright (C) 2020 Free Software Foundation, Inc.
.\"Copying and distribution of this file, with or without modification,
.\"are permitted in any medium without royalty provided the copyright
.\"notice and this notice are preserved.
.\"
.\"Process this file with
.\"groff -man -Tascii nxdisplay.1
.\"
.TH NXDISPLAY 1 "August 2020" GSDE "User Manual"
.SH NAME
nxdisplay \- control display's backlight from the command line
.SH SYNOPSIS
.B nxdisplay [\-\-set <brightness>] [\-\-increase] [\-\-decrease]
.P
.SH DESCRIPTION
.P
Control display's backlight from the command line. 
This command uses OSEDisplay API to do the actual work. 

.SH OPTIONS
.P
\-\-set <brightness>
\-\-increase
\-\-decrease
.P
