.\"nxmount(1) man page
.\"put together by onflapp
.\"Copyright (C) 2020 Free Software Foundation, Inc.
.\"Copying and distribution of this file, with or without modification,
.\"are permitted in any medium without royalty provided the copyright
.\"notice and this notice are preserved.
.\"
.\"Process this file with
.\"groff -man -Tascii nxmount.1
.\"
.TH NXMOUNT 1 "August 2023" GSDE "User Manual"
.SH NAME
nxmount \- mount disks from the command line
.SH SYNOPSIS
.B nxmount <value>
.P
.SH DESCRIPTION
.P
Mount disks from the command line.

.SH OPTIONS
.P
\-\-help
.P
