.\"nxnotify(1) man page
.\"put together by onflapp
.\"Copyright (C) 2020 Free Software Foundation, Inc.
.\"Copying and distribution of this file, with or without modification,
.\"are permitted in any medium without royalty provided the copyright
.\"notice and this notice are preserved.
.\"
.\"Process this file with
.\"groff -man -Tascii nxnotify.1
.\"
.TH NXNOTIFY 1 "August 2020" GNUstep "NEXTSPACE System Manual"
.SH NAME
nxnotify \- send notifications from the command line
.SH SYNOPSIS
.B nxnotify <value>
.P
.SH DESCRIPTION
.P
Send notification from the command line.

.SH OPTIONS
.P
\-\-show-panel \-\-title <text> \-\-info <text>
\-\-show-panel \-\-title <text> \-\-info <text> \-\-hide-panel <timeout>
\-\-hide-panel
\-\-show-message \-\-title <text> \-\-info <text>
.P
