#!/bin/bash

if [ "$1" = "screen" ];then
  W=`xwininfo -root | awk '/Width:/{ print $2 }'`
  H=`xwininfo -root | awk '/Height:/{ print $2 }'`
  ffmpeg -framerate 10 -f x11grab -video_size "${W}x${H}" -i $DISPLAY $2
else
  A=`slop -n 1 -o -f "-video_size %wx%h -i $DISPLAY+%x,%y"`
  if [ -n "$A" ];then
    ffmpeg -framerate 10 -f x11grab $A $2
  fi
fi
