#!/bin/bash

if [ "$1" = "screen" ];then
  /usr/bin/scrot --delay 1 "$2"
  exit
fi
if [ "$1" = "window" ];then
  WID=`xwininfo | awk '/Window id:/{print $4 }'`
  if [ -n "$WID" ];then
    /usr/bin/scrot --b -w $WID "$2"
  fi
  exit
fi

/usr/bin/scrot -b --select "$2"
