#!/bin/perl

sub list_smb_shares {
  my ($a, $p) = @_;
  open(X, "gio list -u smb://$a:$p |");
  while(<X>) {
    chomp();
    s/\/\._/\//;
    print("$_\n");
  }
  close(X);
}

open(IN, "avahi-browse -p -a --resolve -t|");
while(<IN>) {
  chomp();
  if ($_ =~ /^=;/) {
    @a = split(';',$_);
    $n = $a[3];
    $t = $a[4];
    $a = $a[7];
    $p = $a[8];

    if ($t eq "Microsoft Windows Network") {
      list_smb_shares($a, $p);
    }
    elsif ($t eq "WebDAV File Share") {
      print ("$n - $t | $a:$p\n");
    }
  }
}
close(IN);
