# -*- mode: makefile-gmake -*-

ADDITIONAL_INCLUDE_DIRS += -I/Developer/Headers -I../SystemKit/derived_src

ADDITIONAL_OBJCFLAGS += -Wno-import -Wno-unused -pipe -Wno-format-security

LIBRARIES_DEPEND_UPON += -L../SystemKit/SystemKit.framework -lSystemKit -lmagic -lgnustep-gui
