#!/usr/bin/env perl

$DEV=$ARGV[0];

open(IN, "nmcli device show $DEV|");
while(<IN>) {
  chomp();
  $line = $_;
  if (m/^(\w.*?):\s+(.*?)$/) {
    $name = $1;
    $val = $2;
    next if ($val eq "--");
    next if ($val eq "<hidden>");

    print("$line\n");
  }
}
close(IN);
