#!/bin/bash

clear

function exec_sudo {
  echo "=== about to execute command as root ==="
  echo "$1"
  echo ""
  sudo sh -c "$1"
}

case "$1" in
  start)
    exec_sudo "systemctl start $2"
    sleep 1
    systemctl status $2
    ;;
  stop)
    exec_sudo "systemctl stop $2"
    sleep 1
    systemctl status $2
    ;;
  enable)
    exec_sudo "systemctl enable $2"
    sleep 1
    systemctl status $2
    ;;
  disable)
    exec_sudo "systemctl disable $2"
    sleep 1
    systemctl status $2
    ;;
  shutdown)
    echo "your system is going to power off"
    sleep 3
    systemctl poweroff
    ;;
  sleep)
    echo "your system is going to suspend"
    sleep 3
    systemctl suspend
    ;;
  emergency)
    echo "your system is going to go to emergency mode"
    sleep 3
    systemctl rescue --no-block
    ;;
  reboot)
    echo "your system is going to reboot"
    sleep 3
    systemctl reboot
    ;;
esac
