#!/usr/bin/env bash

exec 100> /tmp/gsde-audio-$GS_DESKTOP_ID.lock
flock -n 100 || exit 1

/Library/bin/nxnotify show-panel --title "Audio Volume" --info "increase..." --hide-panel 1
/Library/bin/nxaudio --increase
