#!/usr/bin/env perl

use Time::HiRes qw(usleep);

$HOME = $ENV{'HOME'};
%DONE = ();
@DOCUMENTS = ();
%INFO = ();
$INFO_IN = 0;
$WAIT = 100;

sub lauchproc {
  my ($cmd) = @_;
  open (IN, "$cmd |");
  while (<IN>) {
    chomp();
    if (/{/) {
      %INFO = ();
      $INFO_IN = 1;
    }
    elsif (/}/) {
      $INFO_IN = 0;
      if ($INFO{'AutoLaunch'} eq "Yes") {
        $CMD = $INFO{'Command'};

        if ($INFO{'OneShot'} eq "Yes" && -e $CMD) {
          if ($CMD ne "" && $DONE{$CMD} eq "") {
            $DONE{$CMD} = $CMD;
            push(@DOCUMENTS, $CMD);
          }
        }
        else {
          @a = split('/', $CMD);
          $CMD = $a[$#a];

          if ($CMD ne "" && $DONE{$CMD} eq "") {
            print(STDERR " lauch $CMD\n");
            system("/Library/bin/nxworkspace", "--autolaunch", $CMD);
            $DONE{$CMD} = $CMD;
            usleep($WAIT);
          }
        }
      }
    }
    elsif ($INFO_IN && m/\s*(.*?)\s*=\s*"?(.*?)"?\s*;/) {
      $INFO{$1}=$2;
    }
  }
  close (IN);
}

### launch dock items
print(STDERR "WindowMaker Dock:\n");
lauchproc ("/System/bin/wdread WMState Dock");

### launch workspaces items
print(STDERR "WindowMaker Workspaces:\n");
lauchproc ("/System/bin/wdread WMState Workspaces");

### Startup folder
print(STDERR "Startup Scripts:\n");
while (<$HOME/Library/Startup/*>) {
  $FILE = $_;
  if (-x $FILE) {
    print(STDERR " exec $_\n");
    system($FILE);
  }
  else {
    push(@DOCUMENTS, $FILE);
  }
  usleep($WAIT);
}

### Open documents/files
print(STDERR "Open Documents:\n");
foreach (@DOCUMENTS) {
  $FILE = $_;
  print(STDERR " open $FILE\n");
  system("/Library/bin/nxworkspace", "--open", $FILE);
  usleep($WAIT);
}
