#!/usr/bin/env bash


function show_selector {
  T="/tmp/$$-apps"
  find /Applications -type d -name "*.app" > $T

  SEL=`cat $T | sort | fzf --no-info --color='hl+:4,hl:4,gutter:-1,bg+:0,fg+:4'`
  if [ -d "$SEL" ];then
    /Library/bin/gopen $SEL
  fi
}

if [ -n "$1" ];then
  show_selector
else
  L="/Library/Scripts/ShowLauncher"
  /Library/bin/nxnotify show-console --cmd "$L" --arg "apps"
fi
