#!/bin/sh
#
# /etc/X11/wdm/Xreset
#
# This script is run as root after any X session ends.

# Use common X11 Xreset framework if available
if [ -x /etc/X11/Xreset ]; then
    /etc/X11/Xreset
fi

# Remove the utmp entry for the session
if grep -qs '^use-sessreg' /etc/X11/wdm/wdm.options \
    && which sessreg >/dev/null 2>&1; then
    sessreg -d -l "$DISPLAY" -u /var/run/utmp -x /etc/X11/wdm/Xservers "$USER"
fi

exit 0
